services:
    _defaults:
        public: true

    OroZendeskBundleRestApiController:
        namespace: Oro\Bundle\ZendeskBundle\Controller\Api\Rest\
        resource: '../../Controller/Api/Rest/*Controller.php'
        calls:
            - [setContainer, ['@service_container']]
