Oro\Bundle\ZendeskBundle\Entity\ZendeskRestTransport:
    properties:
        url:
          - NotBlank: ~
          - Length:
              max: 255
        zendeskUserEmail:
          - NotBlank: ~
          - Email: ~
          - Length:
              max: 100
