Oro\Bundle\ZendeskBundle\Entity\ZendeskRestTransport:
    properties:
        url:
          - NotBlank: ~
        email:
          - NotBlank: ~
          - Email:
              mode: strict
        zendeskUserEmail:
          - NotBlank: ~
          - Email: ~
        token:
          - NotBlank: ~
