placeholders:
    placeholders:
        view_content_data_additional_information:
            items:
                oro_zendesk_case_ticket_info: ~

        view_navButtons_before:
            items:
                oro_zendesk_case_sync_button: ~

        breadcrumbs_after:
            items:
                oro_zendesk_authorization_status_label: ~

    items:
        oro_zendesk_case_ticket_info:
            template: '@@OroZendesk/Case/caseTicketInfo.html.twig'
            applicable: "@oro_zendesk.placeholder.filter->isTicketAvailable($entity$)"

        oro_zendesk_case_sync_button:
            template: '@@OroZendesk/Case/syncButton.html.twig'
            applicable: "@oro_zendesk.placeholder.filter->isSyncApplicableForCaseEntity($entity$)"

        oro_zendesk_authorization_status_label:
            template: '@@OroZendesk/OAuth/authStatusLabel.html.twig'
            applicable:
                - '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\IntegrationBundle\Entity\Channel)'
                - '@oro_ui.placeholder.filter->isSame($entity.type$, zendesk)'
