#
# OLD REST API ROUTES
#

oro_api_post_ticket_sync_case:
    path: '/api/rest/{version}/ticket/sync/case/{id}/channel/{channelId}.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\ZendeskBundle\Controller\Api\Rest\TicketController::postSyncCaseAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        channelId: \d+
        _format: json
        version: latest|v1

#
# OAuth ROUTES
#

oro_zendesk_oauth_authorize:
    path: '/zendesk/oauth/authorize/{id}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\ZendeskBundle\Controller\OAuthController::authorizeAction'
    requirements:
        id: \d+

oro_zendesk_oauth_callback:
    path: '/zendesk/oauth/callback'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\ZendeskBundle\Controller\OAuthController::callbackAction'
